### DISCUSSION TITLE
[Covers|Blinds] Completely up or down

### DISCUSSION THREAD

**Discussion by Ruaktom** [MichielVanwelsenaere/HomeAutomation.CoDeSys3#98] [Q&A] [answered]
Hi,

I'm working with a PFC200 through e!cockpit and am trying to make my blinds works using this project (which btw already works splendidly for my switches!).

Currently I've been able to make the following work using the provided examples:
- Making blind go up/down while long pressing a push button
- Making blind go up down completely (or stop) with an MQTT message

What I'm battling with is making making the blinds go completely up or down with a single press on the push button. If the push button is pressed again while the blinds are moving, I would like to make them stop.

Any idea how to achieve this?

Thanks!

Tom

**Comment by MichielVanwelsenaere** [comment, marked as answer]
Hi Tom,

This is actually my first prio tot add to the project. I need it myself as well 😉.

The cover function block is one of the more complex ones in the project. I'm not yet really sure how to implement except that it probably will require a statemachine.

I would expect to have this working in the comming two months. Feel free to give it a try yourself in the meantime, would certainly be good for your PLC skills 😉.

Best regards
Michiel

**Reply by Ruaktom** [reply]
Thanks Michiel,

Wanted to make sure I wasn't missing something before giving it a go. I'll come back here if I find an elegant solution.

Have a nice day,

Tom

**Reply by MichielVanwelsenaere** [reply]
[HomeAutomation_simpleCover.txt](https://github.com/MichielVanwelsenaere/HomeAutomation.CoDeSys3/files/8193338/HomeAutomation_simpleCover.txt)

Hi Tom,

I finally had some time to have a look at this today and got my own covers working with a 'toggle' input.
I've attached an export of the openPLC XML which should allow you to import it in your project (you'll need to rename it to a file with '.xml' extension).

Home Assistant config looks something like the below:
```yaml
- platform: mqtt
  name: "cover myroom"
  state_topic: "Devices/PLC/MyHome/Out/Covers/FB_DO_COVER_2"
  state_open: "OPEN"
  state_closed: "CLOSED"
  command_topic: "Devices/PLC/MyHome/In/Covers/FB_DO_COVER_2"
  payload_open: "OPEN"
  payload_close: "CLOSE"
  payload_stop: "STOP"
  qos: 2
  optimistic: true
  availability_topic: "Devices/PLC/MyHome/availability"
  payload_available: "online"
  payload_not_available: "offline"
```

I'm going to test this for some time and it should be included in the next release as well.
